### ISSUE TITLE
Undefined array key "X-Leaf-CSRF-Token"

### ISSUE THREAD

**Issue by ibnsultan** [leafsphp/csrf#12]
Undefined array key "X-Leaf-CSRF-Token" when calling `\Leaf\Anchor\CSRF::form()`

**Comment by ibnsultan** [comment]
@mychidarko The new version also still restricts for csrf tokens submitted through the body `_token`

**Comment by mychidarko** [comment]
For compatibility with the earlier version, you need to make a little change to your existing config:

```php
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Secret
    |--------------------------------------------------------------------------
    |
    | This is the secret key used to generate the CSRF token. It is
    | combined with a random string to generate the token.
    |
    */
    'secret' => _env('APP_KEY', '@nkor_leaf$0Secret!!'),

    /*
    |--------------------------------------------------------------------------
    | Secret Key
    |--------------------------------------------------------------------------
    |
    | This is the key under which the token will be stored in the
    | session. It can also be used to retrieve the token from the
    | request headers.
    |
    */
    'secretKey' => '_token',

    /*
    |--------------------------------------------------------------------------
    | Route Exceptions
    |--------------------------------------------------------------------------
    |
    | This is a list of routes that will be excluded from CSRF
    | verification. This is useful for APIs that need to bypass
    | the CSRF verification. You can add route URIs or directly pass
    | in dynamic routes like '/items/{id}' or '/items/(\d+)'.
    |
    */
    'except' => [],

    /*
    |--------------------------------------------------------------------------
    | Configure allowed HTTP methods
    |--------------------------------------------------------------------------
    |
    | This is a list of HTTP methods that are the CSRF module will
    | be active on. All other methods will be ignored.
    |
    */
    'methods' => ['POST', 'PUT', 'PATCH', 'DELETE'],

    /*
    |--------------------------------------------------------------------------
    | Configure missing token message
    |--------------------------------------------------------------------------
    |
    | This is the message that will be returned when the CSRF token
    | is not found in the request.
    |
    */
    'messages.tokenNotFound' => 'Token not found.',

    /*
    |--------------------------------------------------------------------------
    | Configure invalid token message
    |--------------------------------------------------------------------------
    |
    | This is the message that will be returned when the CSRF token
    | is invalid.
    |
    */
    'messages.tokenInvalid' => 'Invalid token.',

    /*
    |--------------------------------------------------------------------------
    | Configure error handler
    |--------------------------------------------------------------------------
    |
    | By default, the CSRF module will return a built-in error page,
    | however, you can configure a custom error handler to handle
    | your own error pages.
    |
    | onError: function() {
    |     // Your custom error handler
    | }
    |
    */
    'onError' => null,
];
```

The main thing is changing the secretKey to `_token` as we had in earlier versions

**Comment by ibnsultan** [comment]
@mychidarko Apparently that's what I tried doing first hand, but if that value (X-Leaf-CSRF-Token) is changed to any other value, the return of `Leaf\Anchor\CSRF::token()` for some reasons becomes empty;

**Comment by ibnsultan** [comment]
Found the Issue, that's because the the csrf config file is not registered hence the values used are the hardcorded values in `\Leaf\Anchor::$config`

In the version before the previous version we had a several issues including this which was addressed in PR #8 , where the csrf was not registered so I added inside the overide config function in the `\Leaf\Anchor\CSRF` a condition that [first checks for the csrf config file](https://github.com/leafsphp/csrf/commit/6f90932691ff300f3fe589ba1f4e3384007691d6#diff-1aa5a2736d563a90290b5acedfff510798c07f1f9516556e1d358141c444f0feR30), but it has been removed and neither is it available in `\Leaf\Anchor`

**Comment by mychidarko** [comment]
Oh wait I moved that to mvc-core. So there's no need to add it back here. Upgrading MVC-core should fix your issue

**Comment by ibnsultan** [comment]
I've seen the initialization instance `app()->csrf(Config::getStatic('mvc.config.csrf'))` but some reason it does not work.
could you please recheck because i've set mvc-core to always use the latest version on upgrade, below is my log to the lock file showing that am using the latest version

```json
{
     ...
    "name": "leafs/mvc-core",
    "version": "v1.6.0",
    "source": { ... }
}
```

**Comment by ibnsultan** [comment]
@mychidarko Have you had any breakthrough from your end, I even thought this line could be the [cause](https://github.com/leafsphp/leafMVC/blob/v3.x/composer.json#L33), I have `leafs\leaf` at the LTS too but still without the condition check in the `anchor` package the issue still persists, no `csrf.php` config is used
