### ISSUE TITLE
Undefined global variable $_SESSION

### ISSUE THREAD

**Issue by crosa7** [leafsphp/csrf#2]
Hey Mychi,

To give some context, I have created a Leaf MVC project, wrote some code and then I installed CSRF.
Immediately after this, I reload the page and I get `Undefined global variable $_SESSION` in `vendor/leafs/csrf/src/CSRF.php70`. I debugged a bit and found out this part of the code that throws the exception.
https://github.com/leafsphp/csrf/blob/9ae0d886a0f94ab902deb341493a4d6d36fc8f11/src/CSRF.php#L68

I checked and this is called the first time in here https://github.com/leafsphp/leaf/blob/f2f02d212dafca495bd8de97a8ab36f0ecb79f29/src/App.php#L50

But since the CSRF::init(), where `session_start()` is called, didn't happen yet, we have no `$_SESSION`

Am I seeing this wrong or missing some kind of configuration, or this is really an issue?

Thank you in advance

**Comment by mstraczkowski** [comment]
I've installed `skeleton` and added `csrf` module via composer and the same error has occurred.

**Comment by crosa7** [comment]
> I've installed `skeleton` and added `csrf` module via composer and the same error has occurred.

To solve it I added the `CSRF::init()` in `public/index.php` before `app()->config(AppConfig())` but I guess this is only a temporary fix

**Comment by mychidarko** [comment]
Hi guys, sorry about this. I'm actually just seeing this issue. Once Leaf detects that you have installed the csrf module, it is supposed to automatically setup the CSRF module and initialize everything.

Since this is not happening automatically, it most likely is a bug. I'll check it out and keep this thread updated.

**Comment by mychidarko** [comment]
A new version has been released which should fix this error

**Comment by mychidarko** [comment]
@crosa7 have you been able to check on this? Do you still experience the issue?

**Comment by crosa7** [comment]
It is fixed now, thanks a lot!
