### ISSUE TITLE
How can I use a Post method by the Ajax function (using axios for example)?

### ISSUE THREAD

**Issue by ronaldomussa** [leafsphp/csrf#4]
How can I use a Post method by the Ajax function (using axios for example)?

I am sending the x-csrf-token in the header but doesn't work;

**Comment by ibnsultan** [comment]
Have you tried sending it directly as part of the body with `_token` as your key

**Comment by milosPavic** [comment]
x-csrf-token it is not implemented, the error is in the script itself it use only body checking not a header checking for a token

**Comment by mychidarko** [comment]
You should be able to pass in the X-CSRF-TOKEN header now
